### ISSUE TITLE
Support for handling blocked connections. Possible?

### ISSUE THREAD

**Issue by c-datculescu** [php-amqp/php-amqp#197]
Hello.

It would be useful if php-amqp would support blocked connections notifications. We recently ran in a case in which the rabbitmq cluster we were running ran out of resources, triggering the memory alarm.

In this case all our publisher connections were in status blocked, which in turn kept the entire php pool blocked so new requests could not be delivered anymore.

While investigating how to solve this we didn't found an alternative solution (we played with write_timeout, socket options, pool settings, ini settings without any satisfactory result), and support for this rabbitmq extension would be exactly what we would need (and i assume others as well).

I am not sure about the effort for the implementation or if there are any impediments in implementing it.

Thank you,
Cristian.

**Comment by pinepain** [comment]
Based on a brief look, rabbitmq-c supports [Blocked Connection Notifications](https://www.rabbitmq.com/connection-blocked.html), but there are no examples in rabbitmq-c how to use this feature (https://github.com/alanxz/rabbitmq-c/issues/161), so it may take some time to figure out a bit how it exactly implemented there.

**Comment by c-datculescu** [comment]
Hi and thanks for the fast feedback. On a simple look before opening up the issue we also saw some support for it from version 5.2 up.

We'll try to maybe look these day more closely and post bere if we have any findings.

Best,
Cristian.

**Comment by pinepain** [comment]
I played a bit to implement this feature, and while it is possible, I totally agree with Alan, the rabbitmq-c author:
>  For the API that rabbitmq-c currently exposes, supporting this correctly is difficult.

Literally, implementation will looks like:
```php

$cnn = new AMQPConnection($credentials);
$cnn->connect();

$ch = new AMQPChannel($cnn);

$ex = new AMQPExchange($ch);
$ex->setName('exchange-' . microtime(true));
$ex->setType(AMQP_EX_TYPE_FANOUT);
$ex->declareExchange();

$ex->publish(str_repeat('test', 10000));
$cnn->waitForBlockedConnectionNotifications(1.0);
```

where `waitForBlockedConnectionNotifications` will block current execution thread.

Using synchronous approach with asynchronous AMQP protocol limits number of features can be used, so without entering async loop or using threads, it's hard, if even possible to implement this feature in a sane way.

**Comment by c-datculescu** [comment]
Could it be done with a callback? Kind of in the same style that the publisher acknowledgements is currently implemented in the respective pull request. This might give the option to actually do something else with the messages that would be published (dump them to disk, etc).

**Comment by pinepain** [comment]
@c-datculescu is all about sync/async approach. Sadly, but extension is heavily synchronous, so it is a bit tricky to add blocked connection notification.

**Comment by Umkus** [comment]
Hello, @c-datculescu. Did you happen to come up with a solution/alternative for this over the year?

**Comment by yjqg6666** [comment]
Is it possible to expose receive timeout & write timeout status of the socket to AMQPConnection.

**Comment by lstrojny** [comment]
Closing
