### ISSUE TITLE
No Exception during publish when connection is closed

### ISSUE THREAD

**Issue by maanenh** [php-amqp/php-amqp#245]
When publishing on an exchange no exception is thrown when the connection is closed. See next code fragment: 

``` php
<?php
$connection = new AMQPConnection();
$connection->setHost('localhost');
$connection->setLogin('guest');
$connection->setPassword('guest');
$connection->connect();

//Create and declare channel
$channel = new AMQPChannel($connection);

//Declare Exchange
$exchange = new AMQPExchange($channel);
$exchange->setName('amq.fanout');

$message = 'hello world 1';
$stat=$exchange->publish($message, 'key');
echo " [X] Sent {$message}   return status: {$stat}\n";

echo "sleep 40\n";
echo "Close now the connection in the RabbitMQ management console.\n";
sleep(40);

$message = 'hello world 2';
$stat=$exchange->publish($message, 'key');
echo " [X] Sent {$message}   return status: {$stat}\n";
```

When the connection is closed between publishing the two messages (on the management console), I expected an Exception to be thrown when publishing the second message. Or to receive a false in $stat.

When there is no routing key in the messages it works as expected, but with a routing key there is no exception thrown.

I use PHP7 and installed the amqp extension with  `pecl install amqp`

**Comment by pinepain** [comment]
Hi! Thanks for reporting!

Publishing is asynchronous operation which doesn't require response from server. Basically, under the hood, publish process done by writing data to socket and considering that message was sent. And it is not possible to get whether socket is opened or closed on the other end without actually use. There are [Confirms (aka Publisher Acknowledgements)](https://www.rabbitmq.com/confirms.html) in RabbitMQ to have guaranteed delivery.

Anyway, I'll try to find some time to have a look on this particular scenario. I'm a bit committed last time, so if you or someone else feel strong desire to dive into and provide some patch/PR you are more then welcomed.

**Comment by maanenh** [comment]
Thanx for the quick response.
Without routing key it works as expected and an Exception is thrown....

**Comment by maanenh** [comment]
By the way:
I found a work-around.  By wrapping the publishing in a `$channel->startTransaction();` and a `$channel->commitTransaction();` .
The startTransaction() throws an AMQPException

**Comment by pinepain** [comment]
Yeah, transactions are another way to have more reliable publishes. php-amqp supports both transactions and confirms, so get alongside what you like/fits your needs the best.

AMQP transaction methods (tx.select, tx.commit, tx.rollback) are two way, it means that client waits for transaction start/end confirmation, unlike [basic.publish](http://www.rabbitmq.com/amqp-0-9-1-quickref.html#basic.publish).

Though, I think there are not too much to do about the issue with server closed connections except using transactions or confirms, so your approach is even not a workarond but a standard solution for this sort of problems.

**Comment by lstrojny** [comment]
Closing
