### ISSUE TITLE
consume fetches all messages from queue

### ISSUE THREAD

**Issue by thomasbley** [php-amqp/php-amqp#260]
`<?php
$cnn = new AMQPConnection();
$cnn->connect();

$ch = new AMQPChannel($cnn);
$q = new AMQPQueue($ch);
$q->setName('queue1');
$q->declareQueue();

$ex = new AMQPExchange($ch);
$ex->publish('hello world 1', 'queue1');
$ex->publish('hello world 2', 'queue1');

$q->consume('consume', AMQP_AUTOACK);

$cnn->disconnect();

$cnn = new AMQPConnection();
$cnn->connect();
$ch = new AMQPChannel($cnn);
$q = new AMQPQueue($ch);
$q->setName('queue1');
$q->declareQueue();
$q->consume('consume', AMQP_AUTOACK);

$cnn->disconnect();

function consume($message) {
	echo $message->getBody().PHP_EOL;
	return false;
}`

Output:
hello world 1

Expected output:
hello world 1
hello world 2

I'm using these packages:
php-amqp                         1.7.1-1+deb.sury.org~trusty+1
rabbitmq-server                  3.6.6-1

**Comment by thomasbley** [comment]
using get() gives the expected output:

`<?php
$cnn = new AMQPConnection();
$cnn->connect();

$ch = new AMQPChannel($cnn);
$q = new AMQPQueue($ch);
$q->setName('queue1');
$q->declareQueue();

$ex = new AMQPExchange($ch);
$ex->publish('hello world 1', 'queue1');
$ex->publish('hello world 2', 'queue1');

$msg = $q->get(AMQP_AUTOACK);
echo $msg->getBody().PHP_EOL;

$cnn->disconnect();

$cnn = new AMQPConnection();
$cnn->connect();
$ch = new AMQPChannel($cnn);
$q = new AMQPQueue($ch);
$q->setName('queue1');
$q->declareQueue();

$msg = $q->get(AMQP_AUTOACK);
echo $msg->getBody().PHP_EOL;

$cnn->disconnect();`

output:
hello world 1
hello world 2

**Comment by pinepain** [comment]
Hi, looks weird, as `AMQP_AUTOACK` used, messages should be sent one by one, ignoring `prefetch_count` option.

What PHP, php-amqp and RabbitMQ version do you use?

**Comment by thomasbley** [comment]
here are the packages:
dpkg --list | grep -E "amqp|rabbitmq-server|php7.0-cli"
`ii  php-amqp                         1.7.1-1+deb.sury.org~trusty+1        amd64        AMQP extension for PHP
ii  php7.0-cli                       7.0.14-1+deb.sury.org~trusty+1       amd64        command-line interpreter for the PHP scripting language
ii  rabbitmq-server                  3.6.6-1                              all          Multi-protocol messaging broker`

here is my vagrantfile:
https://gist.github.com/thomasbley/dee226ef4a29d729c83dc64670f22159

here is my bootstrap.sh:
https://gist.github.com/thomasbley/7380eac0b7fbbe276043a2df13d30099

**Comment by thomasbley** [comment]
same results with PHP 5.6.29-1+deb.sury.org~trusty+1

**Comment by lstrojny** [comment]
Closing
