### ISSUE TITLE
Support URIs as connection information

### ISSUE THREAD

**Issue by Taluu** [php-amqp/php-amqp#278]
Currently, you can log-in only with an array containing the `host`, `login`, `password`, and so on. [On the AMQP specs](https://www.rabbitmq.com/uri-spec.html), we should be able to log-in with an URI, like `amqp://foo:bar@locahost:5672/my/vhost`. Especially as `login`, `password`, `vhost` and `port` are optionnal parts.

Any plan to support this ? Thanks

**Comment by pinepain** [comment]
Hi @Taluu, sorry for late response. 

> `[On the AMQP specs](https://www.rabbitmq.com/uri-spec.html)`

To clarify, https://www.rabbitmq.com/uri-spec.html is RabbitMQ URI Specification, not AMQP. 

As Internally php-amqp will have to parse that url into components so it would add unnecessary complexity to extension. Supporting RabbitMQ AMQP URL scheme could be done out of extension codebase in userland with much less efforts and on-needed basis.

**Comment by makasim** [comment]
you can do it If you choose `enqueue/amqp-ext` which is built on top of this awesome extension 

https://github.com/php-enqueue/enqueue-dev/blob/master/docs/transport/amqp.md#create-context

**Comment by lstrojny** [comment]
Closing
