### ISSUE TITLE
Extension license

### ISSUE THREAD

**Issue by pinepain** [php-amqp/php-amqp#288]
php-amqp ext still use PHP license, though extension itself is neither PHP core extension nor relates to PHP/Zend organization, so it might be a good move to start using more popular and well-known license which explicitly covers all usage aspects.

MIT looks like one that just do the job well.

What php-amqp community think about this idea?

@lstrojny do you have any particular thoughts on topic?

### Contributors who need to agree to a license change

- [x] 23006 pinepain@gmail.com
- [ ] 2560 pdezwart@rubiconproject.com
- [x] 2398 lars@strojny.net
- [x] 1219 bkw@codingforce.com
- [ ]  255 sladkov@gmail.com
- [ ]  107 ab@php.net
- [x]   95 sqmk@php.net
- [x]   90 remi@famillecollet.com
- [ ]   88 dizeee@dizeee.ru
- [x]   87 lars.strojny@internations.org
- [ ]   46 vkartaviy@gmail.com
- [ ]   25 peter.hansen@rwth-aachen.de
- [x]   21 lstrojny@lstrojnypro.local
- [ ]   18 github@a.bbnt.me
- [ ]   14 artemjo@gmail.com
- [x]   10 fedora@famillecollet.com
- [ ]    6 saschaprolic@googlemail.com
- [ ]    5 kangur91@gmail.com
- [ ]    4 siad.ardroumli@googlemail.com
- [x]    4 kotlyar.maksim@gmail.com
- [ ]    1 sergsk@gmail.com
- [ ]    1 sergeyklay@users.noreply.github.com
- [ ]    1 lyrixx@lyrixx.info
- [ ]    1 kazuki_yasufuku@dwango.co.jp

**Comment by lstrojny** [comment]
In hindsight I believe using MIT or the Apache license would have been better. Organising a license change is nothing I am personally interested in doing, I would agree to a license change though immediately.

**Comment by lstrojny** [comment]
Here is how to find all contributors and how many lines of code are still 

```
23006 pinepain@gmail.com
2560 pdezwart@rubiconproject.com
2398 lars@strojny.net
1219 bkw@codingforce.com
 255 sladkov@gmail.com
 107 ab@php.net
  95 sqmk@php.net
  90 remi@famillecollet.com
  88 dizeee@dizeee.ru
  87 lars.strojny@internations.org
  46 vkartaviy@gmail.com
  25 peter.hansen@rwth-aachen.de
  21 lstrojny@lstrojnypro.local
  18 github@a.bbnt.me
  14 artemjo@gmail.com
  10 fedora@famillecollet.com
   6 saschaprolic@googlemail.com
   5 kangur91@gmail.com
   4 siad.ardroumli@googlemail.com
   4 kotlyar.maksim@gmail.com
   1 sergsk@gmail.com
   1 sergeyklay@users.noreply.github.com
   1 lyrixx@lyrixx.info
   1 kazuki_yasufuku@dwango.co.jp
```

This is how I got those:
```
git ls-files | while read file ; do git blame -e $file | cat - ; done | awk -F ' \\(\<' '{print $2}' | awk -F ">" '{print $1}' | sort | uniq -c | sort -nr
```

Next step is to email all of them, state the rationale for the license change and ask them to either reply affirmatively or dissenting. We should give our contributors a few weeks to reply and we would then need to refactor the contributions of those who are not dissenting or abstaining.

**Comment by makasim** [comment]
Doctrine used this when they did similar things https://github.com/beberlei/license-manager

**Comment by makasim** [comment]
> 4 kotlyar.maksim@gmail.com

I don't mind

**Comment by lstrojny** [comment]
@bkw @pdezwart @remicollet do you agree to a license change from PHP license to MIT?

**Comment by remicollet** [comment]
@lstrojny BSD could be simpler, as PHP License is already BSD ;)  (+ name protection)

BTW, I'm fine with any "free" license (from fsf list), so ok with MIT.

**Comment by lstrojny** [comment]
Thank you @remicollet !

**Comment by pinepain** [comment]
I second @remicollet and if community will find that BSD fits better, I'm OK with that.

@remicollet you mean the 3-clause BSD one, right?

**Comment by remicollet** [comment]
> @remicollet you mean the 3-clause BSD one, right?

PHP itself  is indeed BSD-3-clause (clase 4, 5, 6 being name protection)

**Comment by remicollet** [comment]
Notice, from recent discussion about sodium extension, switching away from PHP License means, this extension will NOT be mergable in php-src without being relicensed again. (btw, probably don't make sense to be merged in PHP)

**Comment by lstrojny** [comment]
@remicollet I think that's fine since it would never make sense for php-amqp to be part of core PHP

**Comment by bkw** [comment]
> bkw@codingforce.com

I‘m fine with any free license really.

**Comment by lstrojny** [comment]
Thank you @bkw

**Comment by sqmk** [comment]
I'm all good with a license change.

**Comment by lstrojny** [comment]
This effort did not succeed and it’s now too late
