### ISSUE TITLE
amqps instead of amqp

### ISSUE THREAD

**Issue by philippe-gillet** [php-amqp/php-amqp#289]
Hello,

I can't find a way to use amqps protocol instead of amqp with this repository to secure the transport of our messages.
I other words I want to use amqps://... instead of amqp:// 

Is there a way to define it? Or do you plan to allow to define it?

Best regards,

**Comment by pinepain** [comment]
Hi! Thanks for good question, it really worth to add this use case to examples or demo, but unfortunately we don't have it yet done (PRs are welcomed, though).

For now you may take a look at [amqpconnection_ssl.phpt](https://github.com/pdezwart/php-amqp/blob/master/tests/amqpconnection_ssl.phpt) test which demonstrates amqps usage with self-signed certs. Hope, it will help you to get brief idea.

**Comment by philippe-gillet** [comment]
Hello,

I'm trying to install the dev env.
Seems the box is no more available with the current url.

default: Downloading: https://cloud-images.ubuntu.com/vagrant/wily/current/wily-server-cloudimg-amd64-juju-vagrant-disk1.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found

**Comment by pinepain** [comment]
@philippe-gillet thank you reporting the box issue, I'll look into it later today, that's weird. I have in mind to move to another image for a long time, now it's a good time.

**Comment by pinepain** [comment]
@philippe-gillet can we close this? /cc @lstrojny

**Comment by jpastoor** [comment]
I'm trying to get this working without certificates but with username / pass but I can't seem to get it working.

```
$conn = new AMQPConnection([
    "host" => "x",
    "login" => "y",
    "password" => "z",
    'port' => 5671
]);
```

It seems to hang on the connect(). 

Should I open another ticket for this?

**Comment by pinepain** [comment]
@jpastoor having another ticket for your particular issue would be nice. Please, in advance to the issue report, attach some minimal, self-sufficient code to reproduce the issue to speedup troubleshooting.

**Comment by lstrojny** [comment]
Closing
