### ISSUE TITLE
AMQPS Connection using user credentials hangs on connect()

### ISSUE THREAD

**Issue by jpastoor** [php-amqp/php-amqp#292]
I'm trying to connect to an AMQPS server using username/pass.

```
<?php

$conn = new AMQPConnection([
    "host" => "x",
    "login" => "y",
    "password" => "z",
    "port" => 5671,
    "connect_timeout" => 10,
]);

if (!$conn->connect()) {
    throw new Exception("Could not connect to AMQP host");
}

?>
```

This code snippet hangs on the connect() call. 

A similar call via my golang client works fine, so I suspect the problem lies in this library. Is there anyone who is using AMQPS with user credentials instead of certs with any success?

**Comment by pinepain** [comment]
To clarify: the protocol is AMQP and it allows to secure connection with SSL/TLS. When non-secure connection used, `amqp` used to denote the url schema for connection string (not represented in this extension) and for TLS-powered connection `amqps` used.

 AFAIR, php-amqp doesn't provide support for TLS without certs ATM, so you have to specify them or use standard `amqp`  port which is 5672. From your config array it doesn't looks like you are using amqp**S** as you have no certs specified, however you use 5671 port,  which is an amqps-specific port.

**Comment by lstrojny** [comment]
Closing
