### ISSUE TITLE
Proposal: Create interfaces for basic types

### ISSUE THREAD

**Issue by topikito** [php-amqp/php-amqp#294]
Hi!

This is not really an issue, its more of a proposal/question.

We've been using for a while this library (which is great) and today we were wondering why the basic types, as for example,  `AMQPEnvelope` or `AMQPQueue` don't implement any interface.

We don't need right now the interfaces, as we are using the specific classes, but we thought it would decouple the implementation and would be useful for abstracting the concept.

**Comment by makasim** [comment]
They are already there: https://github.com/queue-interop/queue-interop#amqp-interop and AMQP extension is already supported.

**Comment by topikito** [comment]
Thanks for the response @makasim 

I dont really understand what you mean. Im not saying the domain is not following a standard. What Im saying is that, at least on the _stubs_ (Check [AMQPQueue Stub](https://github.com/pdezwart/php-amqp/blob/master/stubs/AMQPQueue.php) for example), theres no implementation of an interface.

**Comment by makasim** [comment]
@topikito  What do you need an interface for?

**Comment by sergeyklay** [comment]
@topikito Do you suggest to move part (some interfaces) of amqp-interop  to  php-amqp? :)

**Comment by topikito** [comment]
@sergeyklay Yes :) That would be it

This is exactly what I mean https://github.com/queue-interop/queue-interop/blob/master/src/PsrQueue.php

**Comment by lstrojny** [comment]
Closing
