### ISSUE TITLE
Removing PHP 5.x support

### ISSUE THREAD

**Issue by pinepain** [php-amqp/php-amqp#298]
Hi there!

The php-amqp extension is a project I like and one of those I heavily contributed and still dedicate my personal time.

As PHP 5.x is out of active support for almost a year and as it will lost security support in almost a year (http://php.net/supported-versions.php) I propose to drop PHP 5.x support completely. As it would be significant BC break, I guess it makes sense to do a major release, which would be `2.x.y`.

Currently in a PHP world we see steady decline of PHP 5.x usage, from Seldaek report (https://seld.be/notes/php-versions-stats-2017-2-edition) it's quite obvious that contributing into PHP 5.x support without serious money in it has no practical sense.

Major PHP frameworks are PHP 7 only (some of them are PHP 7.1 only) or have first-class PHP 7 support (https://gophp71.org)

The plan for current `1.x` branch would be security support only (same as PHP traits 5.x). All further bug fixes which will be reported after we commit to this plan will go to php-amqp `2.x` branch only.

**Comment by pinepain** [comment]
My personal rationale for that is that I can list little if a any issue in this project that was primary reported against PHP 5.x and even less PRs that fixes that.

Currently every single issue that needs to be fixed should be tested against both PHP 5.x and PHP 7.x and taking into account that there are major changes between 5 and 7, it sometimes takes much more time than just fix for single PHP version. This really suck all energy when contributing, I think other contributor wouln't disagree with this.

Now when I have my other open-source project at the top of my list (https://github.com/pinepain/php-v8) and that I really busy at my workplace, have my own pet projects and also have some family commitments, I'm standing before hard choice: whether to cancel all my activities on this project or limit it to what has a future and what is applicable in a long term and cut of the less important and legacy parts.

I don't want to sound ignorant, but honestly I see little ways to contribute towards PHP 5.x unless there will be a serious sponsorship behind such requests.

@lstrojny I'd really appreciate your thoughts on this issue, sure, when you'll have some time.

**Comment by lstrojny** [comment]
I think it makes tons of sense to remove PHP 5 support with a release somewhere at the beginning of next year.

**Comment by pinepain** [comment]
I plan to drop PHP < 7.0 support this month. Any objections? Shall we start new major release for that and move older in maintenance mode (critical bug and security issue fixes)?

**Comment by Algent** [comment]
Hi,
If release 1.9.3 is to be the last one with php5.6 support, could you please publish (or point me to) a set of dll for Windows ?
I've been trying to build them myself for x86 TS but I ran into multiple walls (I'm at the step of trying to build openssl to get rabbitmq to build so I can feed the .lib to build the pecl extension).
Figured I could ask here just in case someone have a working build env.

**Comment by pinepain** [comment]
@Algent you can find some dlls on PECL - https://pecl.php.net/package/amqp

**Comment by lstrojny** [comment]
Removed in 5dab45a0d2f55784ec1ad14f5770fa843c543987
