### ISSUE TITLE
Add Dockerfile for dev needs and for CI

### ISSUE THREAD

**Issue by pinepain** [php-amqp/php-amqp#300]
It came up that segfault in #293 happened only in docker environment, so it make sense to add docker support to CI. 

Based on how popular docker is it's vital to offer Dockerfile for contributors and potential users who'd like to evaluate php-amqp. It may worth to offer docker compose with rabbitmq and maybe nginx and apache, however web servers are optional, imo.

**Comment by lstrojny** [comment]
Fixed in e9c89383da09749b65786bb49a94db590a973f79
