### ISSUE TITLE
Moving php-amqp to organisation account

### ISSUE THREAD

**Issue by pinepain** [php-amqp/php-amqp#304]
Hi @lstrojny and @pdezwart.

Currently, release process is straight and simple, which is a good thing. However, currently it has a bottleneck which is release manager and repo owner. Furthermore, we are currently limited to create a subsplit for, e.g. stubs and make it available from composer and at the same time keep them up to date. 

I'd propose to set up an organization, add owners and admins and transfer php-amqp there. I'd really like to be a part of that organization. I think we can even package php-amqp for early adopters: I already have automated scripts for Ubuntu PPA and macOS Homebrew which, I think we can benefit from.

I see that [php-amqp](https://github.com/php-amqp) name is already taken, is that you? Anyway, the name comes after the decision.

What do you think?

**Comment by lstrojny** [comment]
@pdezwart can we somehow make this happen? I would *love* to see this being done so that I don't stand in the way too much between @pinepain’s great contributions and people actually using it

**Comment by lstrojny** [comment]
This has been done
