### ISSUE TITLE
Library error: a socket error occurred

### ISSUE THREAD

**Issue by sylarzhou** [php-amqp/php-amqp#305]
PHP Fatal error:  Uncaught AMQPException: Library error: a socket error occurred in E:\testWorkspaces\rabbitmqTest\receive2.php:55
Stack trace:
#0 E:\testWorkspaces\rabbitmqTest\receive2.php(55): AMQPQueue->ack(1)
#1 [internal function]: processMessage(Object(AMQPEnvelope), Object(AMQPQueue))
#2 E:\testWorkspaces\rabbitmqTest\receive2.php(41): AMQPQueue->consume('processMessage')
#3 {main}
  thrown in E:\testWorkspaces\rabbitmqTest\receive2.php on line 55

Fatal error: Uncaught AMQPException: Library error: a socket error occurred in E:\testWorkspaces\rabbitmqTest\receive2.php:55
Stack trace:
#0 E:\testWorkspaces\rabbitmqTest\receive2.php(55): AMQPQueue->ack(1)
#1 [internal function]: processMessage(Object(AMQPEnvelope), Object(AMQPQueue))
#2 E:\testWorkspaces\rabbitmqTest\receive2.php(41): AMQPQueue->consume('processMessage')
#3 {main}
  thrown in E:\testWorkspaces\rabbitmqTest\receive2.php on line 55
-------------------------------------------------------------------------------------------------------------------
```
<?php    
//配置信息  
$conn_args = array(  
    'host' => 'localhost',   
    'port' => '5672',   
    'login' => 'guest',   
    'password' => 'guest',  
    'heartbeat'=>'5',
    'vhost'=>'/'  
);    
$e_name = 'e_sylar'; //交换机名  
$q_name = 'q_queue'; //队列名  
$k_route = 'q_queue'; //路由key  
  
//创建连接和channel  
$conn = new AMQPConnection($conn_args);    
if (!$conn->pconnect()) {    
    die("Cannot connect to the broker!\n");    
}
$channel = new AMQPChannel($conn);  
//创建交换机     
$ex = new AMQPExchange($channel);    
$ex->setName($e_name);  
$ex->setType(AMQP_EX_TYPE_DIRECT); //direct类型   
$ex->setFlags(AMQP_DURABLE); //持久化  
echo "Exchange Status:".$ex->declareExchange()."\n";     
//创建队列     
$q = new AMQPQueue($channel);  
$q->setName($q_name);    
$q->setFlags(AMQP_DURABLE); //持久化   
$q->setArgument('x-max-priority', 100);
echo "Message Total:".$q->declareQueue()."\n";    
//绑定交换机与队列，并指定路由键  
echo 'Queue Bind: '.$q->bind($e_name, $k_route)."\n";  
//阻塞模式接收消息  
echo "Message:\n";   
    //$q->consume('processMessage');    
    $q->consume('processMessage');
    //$q->consume('processMessage', AMQP_AUTOACK); //自动ACK应答   

/** 
 * 消费回调函数 
 * 处理消息 
 */  
function processMessage($envelope, $queue) {  
    $msg = $envelope->getBody();  
    echo $msg."\n"; //处理消息  
    for($i=0;$i<30;$i++){
        echo $i.PHP_EOL;
        sleep(1);
    }
    $queue->ack($envelope->getDeliveryTag()); //手动发送ACK应答  
}  
```
![image](https://user-images.githubusercontent.com/26760648/33361434-1acd8c1e-d513-11e7-8cbc-b716b59b0d34.png)

PHP 7.1.4,  php_amqp-1.9.0-7.1

**Comment by pinepain** [comment]
Hi, @sylarzhou! 

You have `heartbeat` set to 5 sec which mean that RabbitMQ will consider connection as dead after 5 sec if there will be no heartbeat response or no network activity on the connection. Later you have  a loop with 30 iterations with `sleep(1)` within and no amqp operations, which literally means `sleep(30)`. This sleep leads to missed heartbeat and connection closed forcibly from RabbitMQ side.

As a further measure you may specify no `hearbeat` value which means default one will be used (`60` in RabbitMQ > 3.0) or specify large enough heartbeat for your tasks.

**Comment by sylarzhou** [comment]
- how to do reconnect the mechanism after conection nreaked off?
![image](https://user-images.githubusercontent.com/26760648/33411072-68f589ae-d5be-11e7-8fbc-ca69d7a2a915.png)
- This code is a simulation of the time-consuming business situation, increase the heart rate is not a solution.
![image](https://user-images.githubusercontent.com/26760648/33411822-b18a2540-d5c2-11e7-9cba-d6a9204698e7.png)

**Comment by pinepain** [comment]
Sorry for late reply, @sylarzhou.

To reconnect AMQP connection you may simply invoke `AMQPConnection::connect()` method on existent connection or create a new connection object, it's up to you. Definitely, you should also support retry/reconnect logic on your application level for that.

As to your question why connection object still exists. This is how it implemented in this extension. The current output if `AMQPConnection::isPersisten() == true` on closed connection is not quite correct, I filled a separate issue for that - #306.

**Comment by lstrojny** [comment]
Closing this issue
