### ISSUE TITLE
AMQPConnection::isPersistent() == true on abruptly closed connection

### ISSUE THREAD

**Issue by pinepain** [php-amqp/php-amqp#306]
As reported in #305. It would be nice to check whether it occurs with properly closed connections.

This issue is a good candidate if someone want's to help with extension and don't know where to start from.

**Comment by lstrojny** [comment]
Same is true for `isConnected()`. My only idea ATM is to actually use the socket and see if it’s still open. Ideas welcome

**Comment by pinepain** [comment]
I recall last time I've looked into this matter the conclusion I came is that unless there is activity on the socket there is no reliable way to tell whether connection is healthy or not. In case of AMQP protocol there is 3 levels where the connectivity could be "abrupt": amqp channel, amqp connection and the network socket. I would basically run some idempotent-like method (one that would have no practical impact on the channel/connection state) on the channel/connection to verify it exists and healthy.  I've also had in mind to pay attention to heartbeats, but relying on this mechanism would likely be a "probabilistic" status of the connection rather then actual. Count in that I didn't touch this extension internals for, ught, at least few years, more like 5 years +, so reality may vary ;)

**Comment by lstrojny** [comment]
Hey @pinepain, glad to hear from you, hope you are ok. You confirmed my suspicion: we would need to start actually do something for `isConnected()` and `isPersistent()`.

**Comment by lstrojny** [comment]
There is unfortunately no way today to generate idempotent socket activity. Checked:

 * `connection.tune` is not idempotent
 * `connection.open`/`connection.start` cannot be called more than once
 * `connection.unblock` cannot be called on a not blocked connection
 * `channel.open` is not idempotent und would waste channels


librabbitmq does not allow sending/receiving heartbeats "by hand" yet (see https://github.com/alanxz/rabbitmq-c/issues/787), that could work.

Documented the lack of reliability of `isConnected` and closing for now as there is nothing we can do.
