### ISSUE TITLE
Optional SSL support

### ISSUE THREAD

**Issue by aimicheng** [php-amqp/php-amqp#310]
Is there any way to disable ssl? 
Because in librabbitmq, ssl is an optional. It can lead the flowing error If librabbitmq not compiled with ssl: 

```
amqp_connection_resource.c:45:29: fatal error: amqp_ssl_socket.h: No such file or directory
 #include <amqp_ssl_socket.h>
                             ^
compilation terminated
```

**Comment by pinepain** [comment]
There is no such feature to disable SSL in php-amqp at the moment. Do you have a specific need to have librabbitmq been built without SSL?

**Comment by lstrojny** [comment]
Closing. Until librabbitmq supports that this is out of scope.
