### ISSUE TITLE
Using SSL requires a CA file, should use the crypto library internal data store

### ISSUE THREAD

**Issue by jvwag** [php-amqp/php-amqp#311]
When using a SSL/TLS secured AMQP connection the current implementation requires given certificate authority file in x509 format.

Real life situations does not always require a determined CA but should use the bundle of CA's as provided with the system running the code. This is probably the default for most API's implementing a secure connection, including for example: the [php stream wrappers](http://php.net/manual/en/migration56.openssl.php). The implementation will use openssl.cafile and openssl.capath in php.ini and sane operating system defaults when not set.

A work-around would be to use the location of the ca bundle as returned by OpenSSL:
```
$conn = new AMQPConnection(['host' => 'hostname', 'port' => 5671, 'login' => 'user', 'password' => 'pass']);
$conn->setCACert(openssl_get_cert_locations()["default_cert_file"]);
$conn->connect();
```

In my opinion a proper implementation of SSL/TLS in php-amqp would be to flag if the connection should use SSL/TLS like other amqp libs (.net/Java: `ConnectionFactory.useSslProtocol();`) and not require a CA file.

For example:

```
// in constructor
$conn = new AMQPConnection(['host' => 'hostname', 'port' => 5671, 'login' => 'user', 'password' => 'pass', 'enable_ssl' => true]);

// as method
$conn->setSSL(true);
```

I'm not too familiar with the amqp-c implementation, but just creating a new parameter and using that as a flag for TLS/SSL usage may solve this issue.

**Comment by pinepain** [comment]
Hi @jvwag. Yeah, current implementation is kludge and what you suggest is far more superior and should take away some (if not all) ssl-related pita away. Do you have in your minds to provide a PR for that by chance?

**Comment by kornerita** [comment]
Hi,

I stumble with this same issue but and found this workaround too late, after compiling and reading c source code...

The librabbitmq library supports ssl connection without issuing the client certificate as shown in the examples
[here](https://github.com/alanxz/rabbitmq-c/blob/a65c64c0efd883f3e200bd8831ad3ca066ea523c/examples/amqp_ssl_connect.c#L102), I also tested it and it works just fine.

Just add a setSsl method and correct [this](https://github.com/pdezwart/php-amqp/blob/5cae72d92a7e2e167cbcbd703c04887159428fd5/amqp_connection_resource.c#L408) if to use that parameter, I believe it should do the work.

Thanks!
Federico.

**Comment by stof** [comment]
> The librabbitmq library supports ssl connection without issuing the client certificate as shown in the examples [here](https://github.com/alanxz/rabbitmq-c/blob/a65c64c0efd883f3e200bd8831ad3ca066ea523c/examples/amqp_ssl_connect.c#L102), I also tested it and it works just fine.

but this example does not verify the peer or the hostname when it does not have a cacert, so it does not protect from MitM as *any* certificate is accepted.

**Comment by lstrojny** [comment]
Closing
