### ISSUE TITLE
Update the reflection info for `AMQPExchange::bind()`

### ISSUE THREAD

**Issue by thePanz** [php-amqp/php-amqp#319]
Adding an issue as a followup for: https://github.com/phpstan/phpstan/issues/1011

**Comment by pinepain** [comment]
Hi! Thanks for reporting. What `php-amqp` version yields that issue?

**Comment by thePanz** [comment]
```bash
$ php --re amqp | head -1
# Extension [ <persistent> extension #17 amqp version 1.9.0 ] {
```
And php:
```bash
$ php -v
# PHP 7.1.16-1+ubuntu14.04.1+deb.sury.org+1 (cli) (built: Apr  5 2018 10:49:09) ( NTS )
# Copyright (c) 1997-2018 The PHP Group
# Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
#    with Zend OPcache v7.1.13-1+ubuntu14.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by thePanz** [comment]
Any updates @pinepain ?

**Comment by pinepain** [comment]
@thePanz oh, sorry man, I totally lost this issue. It's almost anniversary 😄 . 

Unfortunately, I don't have free time to look into this issue but from what written in the linked phpstan issue, it's required to ensure php reflection return valid result and optionally update https://github.com/pdezwart/php-amqp/blame/master/amqp_exchange.c#L816-L820 if it's invalid. From actual method params spec (https://github.com/pdezwart/php-amqp/blame/master/amqp_exchange.c#L649) it looks like there is some discrepancy as in method parmas parsing we write `"s|sa"` which means one param is required and two are optional, and at arginfo (https://github.com/pdezwart/php-amqp/blame/master/amqp_exchange.c#L816) we write that there is two required params, I think it should be just one as per method args parsing string. Feels free to look into this, it shouldn't be a hard pick and if you (or anybody else who are willing to provide a fix) will have any questions, I'll do my best to assist.

**Comment by internalsystemerror** [comment]
I believe the reflection information for AMQPQueue $delivery_tag is incorrect also, as phpstan says that a string is expected but the extension itself throws an error for anything other than an integer. I don't know C all that well, so I'm unable to assist more than this.

**Comment by lstrojny** [comment]
Fixed
