### ISSUE TITLE
Boolean return values (always true?) while also throwing exceptions

### ISSUE THREAD

**Issue by Tobion** [php-amqp/php-amqp#331]
All the provided methods by this extension seem to return a boolean value indicating success like `AMQPExchange::publish`

https://github.com/pdezwart/php-amqp/blob/a910f7e1d7f61f5c62604c97997e8bb41e00c44f/stubs/AMQPExchange.php#L169-L175

At the same time they also throw exceptions. Doing both does not make sense at all and makes any failure handling ugly and duplicate effort.

Then I was looking at the code

https://github.com/pdezwart/php-amqp/blob/a910f7e1d7f61f5c62604c97997e8bb41e00c44f/amqp_exchange.c#L615-L628

and it seems error codes from the c-library are actually transformed to exceptions (which is good 👍 ) and the php binding always returns true. What's the value of always returning true? You could just remove the return value and make it `void`. This way it would be much less confusing to use. This problem seems to apply to alot of methods.

As removing the return value would be a BC break (for next major, ref. #257), we could at least change the phpdoc of the stubs now to mention it always returns true?!

**Comment by lstrojny** [comment]
While it is technically a BC break, I consider this a bug fix. Happy to get a PR on this.

**Comment by lstrojny** [comment]
Fixed for 2.0.0
