### ISSUE TITLE
add support AppVeyor

### ISSUE THREAD

**Issue by macintoshplus** [php-amqp/php-amqp#336]
Can you add the App Veyor build with artefact for produce new prebuilt dll for Windows ?

I have build the master branch for PHP 7.3. 
The artefact is available here: https://ci.appveyor.com/project/macintoshplus/php-win/build/artifacts

**Comment by stof** [comment]
Well, another option would be to make a stable release (see #337) and rely on the fact that pecl.php.net already builds the Windows ddl automatically.

**Comment by macintoshplus** [comment]
Sure, I prefer download from the PECL website. But how-to request the rebuild on PECL website for old version?
Otherwise, the AppVeyor support can provide preview and testing artifacts... In my case, I can use it for testing the PHP 7.3 supports on my applications.

**Comment by macintoshplus** [comment]
Nope, I want to say the "older" for the version 1.9.3 in reference to master branches.

This issue subject is to add the support of AppVeyor for building the master branch and pull request. In fact, the build can add most early support of new PHP version after creating a branch on php-src repository.

**Comment by lstrojny** [comment]
Closing
