### ISSUE TITLE
php 5.6.8 Segmentation fault

### ISSUE THREAD

**Issue by binglangaimo** [php-amqp/php-amqp#342]
comsume a message, prompt Segmentation fault. Please help you! It is urgent!
uname -a
Linux YX-DEV 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.0.1406 (Core) 
Release:	7.0.1406
Codename:	Core

rabbitmq version: 3.7.12

php --ri amqp
Version => 1.9.4
Revision => release
Compiled => Mar  6 2019 @ 23:07:22
AMQP protocol version => 0-9-1
librabbitmq version => 0.8.0
Default max channels per connection => 256
Default max frame size => 131072
Default heartbeats interval => 0

Directive => Local Value => Master Value
amqp.host => localhost => localhost
amqp.vhost => / => /
amqp.port => 5672 => 5672
amqp.timeout => no value => no value
amqp.read_timeout => 0 => 0
amqp.write_timeout => 0 => 0
amqp.connect_timeout => 0 => 0
amqp.login => guest => guest
amqp.password => guest => guest
amqp.auto_ack => 0 => 0
amqp.prefetch_count => 3 => 3
amqp.channel_max => 256 => 256
amqp.frame_max => 131072 => 131072
amqp.heartbeat => 0 => 0
amqp.cacert => no value => no value
amqp.cert => no value => no value
amqp.key => no value => no value
amqp.verify => 1 => 1
amqp.sasl_method => 0 => 0

**Comment by binglangaimo** [comment]
php -v:
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies

**Comment by dercoder** [comment]
I have the same issue with PHP 7.2 since my update from PHP 5.6 to 7.2

lsb_release -a
```
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID: AmazonAMI
Description:    Amazon Linux AMI release 2018.03
Release:        2018.03
Codename:       n/a
```

php --ri amqp
```
Version => 1.9.4
Revision => release
Compiled => Mar 30 2019 @ 13:11:53
AMQP protocol version => 0-9-1
librabbitmq version => 0.8.0
Default max channels per connection => 256
Default max frame size => 131072
Default heartbeats interval => 0

Directive => Local Value => Master Value
amqp.host => localhost => localhost
amqp.vhost => / => /
amqp.port => 5672 => 5672
amqp.timeout => no value => no value
amqp.read_timeout => 0 => 0
amqp.write_timeout => 0 => 0
amqp.connect_timeout => 0 => 0
amqp.login => guest => guest
amqp.password => guest => guest
amqp.auto_ack => 0 => 0
amqp.prefetch_count => 3 => 3
amqp.channel_max => 256 => 256
amqp.frame_max => 131072 => 131072
amqp.heartbeat => 0 => 0
amqp.cacert => no value => no value
amqp.cert => no value => no value
amqp.key => no value => no value
amqp.verify => 1 => 1
amqp.sasl_method => 0 => 0
```

php -v
```
PHP 7.2.16 (cli) (built: Mar  8 2019 18:56:55) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans
```

strace
```
sendto(4, "\1\0\1\0\0\0\r\0<\0P\0\0\0\0\0\0\0\4\0\316", 21, MSG_NOSIGNAL, NULL, 0) = 21
recvfrom(4, 0x28b0aa0, 131072, 0, 0, 0) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=4, events=POLLIN}], 1, 4294967295) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "\1\0\1\0\0\0>\0<\0<\37amq.ctag-VmLH0G-E31-"..., 131072, 0, NULL, NULL) = 7179
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=0} ---
+++ killed by SIGSEGV +++
Segmentation fault
```

**Comment by HemeraOne** [comment]
I got some more info.


uname -a
`
Linux dev1 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`

cat /etc/issue
`
Ubuntu 18.04.2 LTS \n \l
`

php -v
`
PHP 7.2.19-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May 31 2019 11:17:15) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
`

php amqp consumer:

`
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f8dd040b187 in kill () at ../sysdeps/unix/syscall-template.S:78
78      ../sysdeps/unix/syscall-template.S: No such file or directory.
`

(gdb) bt
`
#0  0x00007f8dd040b187 in kill () at ../sysdeps/unix/syscall-template.S:78
#1  0x000055db06c10843 in ?? ()
#2  0x000055db06c10972 in ?? ()
#3  <signal handler called>
#4  0x00007f8dccd0c152 in zim_amqp_queue_class_consume (execute_data=<optimized out>, return_value=0x7fffc320bb90) at /home/martijn/temp/php-amqp/amqp_queue.c:625
#5  0x000055db06c28b9b in ?? ()
#6  0x000055db06c9626c in zend_vm_call_opcode_handler ()
#7  0x000055db06ca16b4 in ?? ()
#8  0x00007f8dbf4e2f2b in nr_php_execute_file () at /home/hudson/workspace/php-bigchange-agent/label/centos5-64-nrcamp/agent/php_execute.c:897
#9  nr_php_execute_enabled () at /home/hudson/workspace/php-bigchange-agent/label/centos5-64-nrcamp/agent/php_execute.c:1106
#10 0x00007f8dbf4e3362 in nr_php_execute () at /home/hudson/workspace/php-bigchange-agent/label/centos5-64-nrcamp/agent/php_execute.c:1340
#11 0x000055db06c959c7 in zend_execute ()
#12 0x000055db06ca03d8 in ?? ()
#13 0x000055db06cb1f28 in phpdbg_stack_execute ()
#14 0x000055db06ca11e6 in ?? ()
#15 0x000055db06a2d101 in ?? ()
#16 0x00007f8dd03edb97 in __libc_start_main (main=0x55db06a2ba30, argc=8, argv=0x7fffc320cf48, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffc320cf38) at ../csu/libc-start.c:310
#17 0x000055db06a2d7fa in _start ()
`


(gdb) frame 4
`
#4  0x00007f8dccd0c152 in zim_amqp_queue_class_consume (execute_data=<optimized out>, return_value=0x7fffc320bb90) at /home/martijn/temp/php-amqp/amqp_queue.c:625
625                     amqp_rpc_reply_t res = amqp_consume_message(channel_resource->connection_resource->connection_state, &envelope, tv_ptr, 0);
`


(gdb) info frame
`
Stack level 4, frame at 0x7fffc320bb90:
 rip = 0x7f8dccd0c152 in zim_amqp_queue_class_consume (/home/martijn/temp/php-amqp/amqp_queue.c:625); saved rip = 0x55db06c28b9b
 called by frame at 0x7fffc320bbe0, caller of frame at 0x7fffc320b780
 source language c.
 Arglist at 0x7fffc320b778, args: execute_data=<optimized out>, return_value=0x7fffc320bb90
 Locals at 0x7fffc320b778, Previous frame's sp is 0x7fffc320bb90
 Saved registers:
  rbx at 0x7fffc320bb58, rbp at 0x7fffc320bb60, r12 at 0x7fffc320bb68, r13 at 0x7fffc320bb70, r14 at 0x7fffc320bb78, r15 at 0x7fffc320bb80, rip at 0x7fffc320bb88
(gdb) info args
execute_data = <optimized out>
return_value = 0x7fffc320bb90
`

(gdb) info locals
`
message = {value = {lval = 140246687054720, dval = 6.9291070016785428e-310, counted = 0x7f8db9f67b80, str = 0x7f8db9f67b80, arr = 0x7f8db9f67b80, obj = 0x7f8db9f67b80, res = 0x7f8db9f67b80, ref = 0x7f8db9f67b80, ast = 0x7f8db9f67b80,
    zv = 0x7f8db9f67b80, ptr = 0x7f8db9f67b80, ce = 0x7f8db9f67b80, func = 0x7f8db9f67b80, ww = {w1 = 3119938432, w2 = 32653}}, u1 = {v = {type = 8 '\b', type_flags = 4 '\004', const_flags = 0 '\000', reserved = 0 '\000'},
    type_info = 1032}, u2 = {next = 0, cache_slot = 0, lineno = 0, num_args = 0, fe_pos = 0, fe_iter_idx = 0, access_flags = 0, property_guard = 0, extra = 0}}
envelope = {channel = 1, consumer_tag = {len = 31, bytes = 0x55db0921e190}, delivery_tag = 2, redelivered = 0, exchange = {len = 15, bytes = 0x55db091eaa70}, routing_key = {len = 28, bytes = 0x55db0921d4a0}, message = {properties = {
      _flags = 40960, content_type = {len = 10, bytes = 0x55db090945b0}, content_encoding = {len = 0, bytes = 0x0}, headers = {num_entries = 5, entries = 0x55db090945c0}, delivery_mode = 0 '\000', priority = 0 '\000', correlation_id = {
        len = 0, bytes = 0x0}, reply_to = {len = 0, bytes = 0x0}, expiration = {len = 0, bytes = 0x0}, message_id = {len = 0, bytes = 0x0}, timestamp = 0, type = {len = 0, bytes = 0x0}, user_id = {len = 0, bytes = 0x0}, app_id = {
        len = 0, bytes = 0x0}, cluster_id = {len = 0, bytes = 0x0}}, body = {len = 484436, bytes = 0x55db09233100}, pool = {pagesize = 4096, pages = {num_blocks = 0, blocklist = 0x0}, large_blocks = {num_blocks = 0, blocklist = 0x0},
      next_page = 0, alloc_block = 0x0, alloc_used = 0}}}
key = <optimized out>
params = {value = {lval = 140246683895440, dval = 6.9291068455893714e-310, counted = 0x7f8db9c64690, str = 0x7f8db9c64690, arr = 0x7f8db9c64690, obj = 0x7f8db9c64690, res = 0x7f8db9c64690, ref = 0x7f8db9c64690, ast = 0x7f8db9c64690,
    zv = 0x7f8db9c64690, ptr = 0x7f8db9c64690, ce = 0x7f8db9c64690, func = 0x7f8db9c64690, ww = {w1 = 3116779152, w2 = 32653}}, u1 = {v = {type = 7 '\a', type_flags = 20 '\024', const_flags = 0 '\000', reserved = 0 '\000'},
    type_info = 5127}, u2 = {next = 1438413712, cache_slot = 1438413712, lineno = 1438413712, num_args = 1438413712, fe_pos = 1438413712, fe_iter_idx = 1438413712, access_flags = 1438413712, property_guard = 1438413712,
    extra = 1438413712}}
retval = {value = {lval = 94399203818400, dval = 4.6639403601437263e-310, counted = 0x55db0702bba0 <compiler_globals>, str = 0x55db0702bba0 <compiler_globals>, arr = 0x55db0702bba0 <compiler_globals>,
    obj = 0x55db0702bba0 <compiler_globals>, res = 0x55db0702bba0 <compiler_globals>, ref = 0x55db0702bba0 <compiler_globals>, ast = 0x55db0702bba0 <compiler_globals>, zv = 0x55db0702bba0 <compiler_globals>,
    ptr = 0x55db0702bba0 <compiler_globals>, ce = 0x55db0702bba0 <compiler_globals>, func = 0x55db0702bba0 <compiler_globals>, ww = {w1 = 117619616, w2 = 21979}}, u1 = {v = {type = 1 '\001', type_flags = 0 '\000',
      const_flags = 0 '\000', reserved = 0 '\000'}, type_info = 1}, u2 = {next = 32767, cache_slot = 32767, lineno = 32767, num_args = 32767, fe_pos = 32767, fe_iter_idx = 32767, access_flags = 32767, property_guard = 32767,
    extra = 32767}}
res = <optimized out>
rv = {value = {lval = 140736467089920, dval = 6.9533053506196664e-310, counted = 0x7fffc320ba00, str = 0x7fffc320ba00, arr = 0x7fffc320ba00, obj = 0x7fffc320ba00, res = 0x7fffc320ba00, ref = 0x7fffc320ba00, ast = 0x7fffc320ba00,
    zv = 0x7fffc320ba00, ptr = 0x7fffc320ba00, ce = 0x7fffc320ba00, func = 0x7fffc320ba00, ww = {w1 = 3273701888, w2 = 32767}}, u1 = {v = {type = 0 '\000', type_flags = 59 ';', const_flags = 101 'e', reserved = 125 '}'},
    type_info = 2103786240}, u2 = {next = 1438413712, cache_slot = 1438413712, lineno = 1438413712, num_args = 1438413712, fe_pos = 1438413712, fe_iter_idx = 1438413712, access_flags = 1438413712, property_guard = 1438413712,
    extra = 1438413712}}
consumer_tag_zv = <optimized out>
current_channel_zv = {value = {lval = 140246683675128, dval = 6.9291068347045124e-310, counted = 0x7f8db9c2e9f8, str = 0x7f8db9c2e9f8, arr = 0x7f8db9c2e9f8, obj = 0x7f8db9c2e9f8, res = 0x7f8db9c2e9f8, ref = 0x7f8db9c2e9f8,
    ast = 0x7f8db9c2e9f8, zv = 0x7f8db9c2e9f8, ptr = 0x7f8db9c2e9f8, ce = 0x7f8db9c2e9f8, func = 0x7f8db9c2e9f8, ww = {w1 = 3116558840, w2 = 32653}}, u1 = {v = {type = 8 '\b', type_flags = 4 '\004', const_flags = 0 '\000',
      reserved = 0 '\000'}, type_info = 1032}, u2 = {next = 32767, cache_slot = 32767, lineno = 32767, num_args = 32767, fe_pos = 32767, fe_iter_idx = 32767, access_flags = 32767, property_guard = 32767, extra = 32767}}
current_queue_zv = <optimized out>
channel_resource = 0x7f8db9ffd768
current_channel_resource = <optimized out>
fci = {size = 56, function_name = {value = {lval = 140246683539584, dval = 6.929106828007749e-310, counted = 0x7f8db9c0d880, str = 0x7f8db9c0d880, arr = 0x7f8db9c0d880, obj = 0x7f8db9c0d880, res = 0x7f8db9c0d880, ref = 0x7f8db9c0d880,
      ast = 0x7f8db9c0d880, zv = 0x7f8db9c0d880, ptr = 0x7f8db9c0d880, ce = 0x7f8db9c0d880, func = 0x7f8db9c0d880, ww = {w1 = 3116423296, w2 = 32653}}, u1 = {v = {type = 8 '\b', type_flags = 4 '\004', const_flags = 0 '\000',
        reserved = 0 '\000'}, type_info = 1032}, u2 = {next = 0, cache_slot = 0, lineno = 0, num_args = 0, fe_pos = 0, fe_iter_idx = 0, access_flags = 0, property_guard = 0, extra = 0}}, retval = 0x7fffc320b840, params = 0x0,
  object = 0x7f8db9f90900, no_separation = 1 '\001', param_count = 0}
fci_cache = {initialized = 1 '\001', function_handler = 0x7f8db9c0d8b8, calling_scope = 0x7f8db9c0f368, called_scope = 0x7f8db9c0f368, object = 0x7f8db9f90900}
arguments = <optimized out>
consumer_tag = 0x0
consumer_tag_len = 0
flags = 0
channel_zv = <optimized out>
consumers = <optimized out>
channel = <optimized out>
tv = {tv_sec = 301, tv_usec = 0}
tv_ptr = 0x7fffc320b810
read_timeout = <optimized out>
`

**Comment by jspeedz** [comment]
Any update on this issue?

**Comment by dercoder** [comment]
In my case i get this segmentation fault when i send igbinary serialized data. 
See: https://github.com/pdezwart/php-amqp/issues/344

**Comment by lstrojny** [comment]
Closing
