### ISSUE TITLE
Expose constants for common delivery modes

### ISSUE THREAD

**Issue by stof** [php-amqp/php-amqp#343]
Clients in Java, Go, Dart, Javascript, Kotlin (maybe using the Java client actually, not sure), DotNet, Ruby and maybe others have a way to publish a message as persistent without hardcoding a `2` in the code.
php-amqp does not have this (Python and Erland do not seem to have it either, or at least https://github.com/rabbitmq/rabbitmq-tutorials/ does not use it).

Exposing constants for transient (`1`) and persistent (`2`) modes would be the simplest way to avoid that (and is what Java and Go are doing as well).
Another option would be to build a dedicated properties object, which would have a `persistent` boolean field, turned back into the delivery mode (this is what Javascript, DotNet and Ruby are doing) but this would not fit in the current API.

**Comment by lstrojny** [comment]
@stof constants sound good. Want to give it a shot?

**Comment by stof** [comment]
Well, I would have to read a tutorial about writing PHP extensions first...
