### ISSUE TITLE
AMQPEnvelope::getBody returns false instead of empty string

### ISSUE THREAD

**Issue by Tobion** [php-amqp/php-amqp#351]
`AMQPEnvelope::getBody` returns false instead of an empty string. See https://github.com/pdezwart/php-amqp/blob/a531e2861d45b999beafc2c04f68ca9d299e63b3/amqp_envelope.c#L99-L102

This is very unexpected and breaks typehints, esp. since it's not documented in
https://github.com/pdezwart/php-amqp/blob/a531e2861d45b999beafc2c04f68ca9d299e63b3/stubs/AMQPEnvelope.php#L15-L17

**Comment by lstrojny** [comment]
Yes, this looks like a bug. Can you open a PR for it?

**Comment by lstrojny** [comment]
Fixed in 939d9afbb8c6a0cece9d6d57e779a487ea45a840
