### ISSUE TITLE
Lack of timeout support per consumer in AMQPQueue::consume

### ISSUE THREAD

**Issue by sicarrots** [php-amqp/php-amqp#352]
Hi all,

I'm trying to implement custom communication library based on rabitmq and php-amqp.
Lots of libraries supporting rabbitmq like PhpAmqpLib and libraries in other languages supports consuming messages with customised timeout. The problem is when we're trying to setup an global consumer in library on main "events" queue, and some local consumers for amq.reply-to pseudo-queues to handle queries/rpc over rabbitmq. Only one possibility to do this which I was found to be possible is to create another connection with different timeouts. 

May I'm missing something? Or maybe is worth to consider adding timeout parameter support to consume method on queue?

**Comment by ZhukV** [comment]
Yes, in this library support only use timeout per connection (`read_timeout`, `write_timeout`). In other libraries this support only on application layer with use timeout on `select`.

**Comment by lstrojny** [comment]
Closing
