### ISSUE TITLE
Trouble getting things rolling with the lib

### ISSUE THREAD

**Issue by eagle275** [php-amqp/php-amqp#377]
As title says - I have problems getting my first examples started .

I followed the setup procedure described in readme.md by using composer to install it ,

then created a simple send.php , using 
`<?php
require_once __DIR__ . '/vendor/autoload.php';
use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Message\AMQPMessage;

$connection = new AMQPStreamConnection('192.168.3.66', 5672, 'guest', 'guest');
$channel = $connection->channel();

$channel->queue_declare('hello', false, false, false, false);

$msg = new AMQPMessage('Hello World!');
$channel->basic_publish($msg, '', 'hello');

echo " [x] Sent 'Hello World!'\n";

$channel->close();
$connection->close();` 
- this is basically the send sample provided in the rabbitmq docs "hello world" - with the only exception that I connect to a running ActiveMQ server in our local network instead to localhost

but I end up with 
`d:\php>php -f send.php
PHP Fatal error:  Uncaught PhpAmqpLib\Exception\AMQPInvalidFrameException: Invalid frame type 65 in D:\php\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Connection\AbstractConnection.php:571
Stack trace:
#0 D:\php\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Connection\AbstractConnection.php(623): PhpAmqpLib\Connection\AbstractConnection->wait_frame()
#1 D:\php\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Channel\AbstractChannel.php(234): PhpAmqpLib\Connection\AbstractConnection->wait_channel()
#2 D:\php\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Channel\AbstractChannel.php(352): PhpAmqpLib\Channel\AbstractChannel->next_frame()
#3 D:\php\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Connection\AbstractConnection.php(245): PhpAmqpLib\Channel\AbstractChannel->wait()
#4 D:\php\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Connection\AbstractConnection.php(217): PhpAmqpLib\Connection\AbstractConnection->connect()
#5 D:\php\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Connection\AMQPStreamConnection.php(60): PhpAmqpLib\Connection\AbstractConnection->__c in D:\php\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Connection\AbstractConnection.php on line 571

Fatal error: Uncaught PhpAmqpLib\Exception\AMQPInvalidFrameException: Invalid frame type 65 in D:\php\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Connection\AbstractConnection.php:571
Stack trace:
#0 D:\php\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Connection\AbstractConnection.php(623): PhpAmqpLib\Connection\AbstractConnection->wait_frame()
#1 D:\php\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Channel\AbstractChannel.php(234): PhpAmqpLib\Connection\AbstractConnection->wait_channel()
#2 D:\php\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Channel\AbstractChannel.php(352): PhpAmqpLib\Channel\AbstractChannel->next_frame()
#3 D:\php\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Connection\AbstractConnection.php(245): PhpAmqpLib\Channel\AbstractChannel->wait()
#4 D:\php\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Connection\AbstractConnection.php(217): PhpAmqpLib\Connection\AbstractConnection->connect()
#5 D:\php\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Connection\AMQPStreamConnection.php(60): PhpAmqpLib\Connection\AbstractConnection->__c in D:\php\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Connection\AbstractConnection.php on line 571`
And yes - its a php 7.4 installation on windows 10 

Did I just miss some prerequisites - or Where could the errors result from ? 

When checking the said AbstractConnection.php on lines around 571 - its the wait_frame function .. even though I want to send, this function wants to read from the amqp "server" ... I can access the amqp broker just fine using amqpdotnetlite from here - so it shouldnt be a problem of network connectivity. 
Any help to get me started using php would be greatly appreciated!

**Comment by lstrojny** [comment]
Your stack trace indicates you are using https://github.com/php-amqplib/php-amqplib, not this library. 

Closing this.

**Comment by eagle275** [comment]
hm .. but i followed the guide from here to install it ... strange 'ne ?
