### ISSUE TITLE
Include a installation instructions for Windows Users

### ISSUE THREAD

**Issue by rezehnde** [php-amqp/php-amqp#382]
I have had stuck for almost two hours figuring out how to enable this extension on Windows 10 running PHP 7.4 After a couple of hours, I realized that we have to copy the rabbitmq.4.dll and rabbitmq.4.pdb to PHP root directory. As we have the CREDITS and LICENSE file, it would be nice to have a README file with instructions like these: https://dev.to/rezehnde/how-to-install-amqp-extension-for-php-7-4-on-windows-10-108d

**Comment by lstrojny** [comment]
@rezehnde great idea. I am not a Windows user myself, do you want to open a PR and give it a shot?

**Comment by rezehnde** [comment]
Done @lstrojny https://github.com/php-amqp/php-amqp/pull/394
