### ISSUE TITLE
Use GitHub actions for CI

### ISSUE THREAD

**Issue by lstrojny** [php-amqp/php-amqp#389]
Travis CI is no longer attractive for Open Source projects, so we should switch to GitHub Actions for Linux and Windows CI.

First objective should be to get a Linux build going as AppVeyor works fine for Windows builds.

**Comment by lyrixx** [comment]
Could be closed I guess

**Comment by lstrojny** [comment]
Leaving open for Windows builds

**Comment by lstrojny** [comment]
Closing

**Comment by lyrixx** [comment]
You forgot to close the issue :)
