### ISSUE TITLE
use php 7.4.16 install failed ext amqp version 1.94  on Mac and centos7.3

### ISSUE THREAD

**Issue by qizekai** [php-amqp/php-amqp#393]
use php 7.4.16 install ext amqp 1.94 failed ,The software is makeing failed but ./configure success
then I try amqp 1.9.0 same failed 

cmd:
./configure --with-php-config=/usr/local/opt/php@7.4/bin/php-config --with-librabbitmq-dir=/usr/local/rabbitmq-c  --with-amqp

explode question:
./php7_support.h:78:3: note: expanded from macro
      'PHP5to7_ZEND_HASH_FOREACH_KEY_VAL'
  ZEND_HASH_FOREACH_KEY_VAL((ht), (num_key), (real_key), (val))
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/php@7.4/7.4.16/include/php/Zend/zend_hash.h:1005:5: note:
      expanded from macro 'ZEND_HASH_FOREACH_KEY_VAL'
        _h = _p->h; \
        ~~ ^
/download/amqp-1.9.4/amqp_type.c:185:8: warning: expression result unused
      [-Wunused-value]
        ulong index;
              ^~~~~
5 warnings and 9 errors generated.
make: *** [amqp_type.lo] Error 1

**Comment by qizekai** [comment]
Mac version:10.14.6
Centos version:7.3

**Comment by lstrojny** [comment]
Should be fixed in the latest version
