### ISSUE TITLE
Is it working for PHP v8 ?

### ISSUE THREAD

**Issue by cybercitizen7** [php-amqp/php-amqp#397]
Hej guys,

I am trying to isntall amqp according to installation steps, but I receive error:
`PHP Warning:  PHP Startup: Unable to load dynamic library 'amqp' (tried: ext\amqp (The specified module could not be found), ext\php_amqp.dll (The specified module could not be found)) in Unknown on line 0`

I am using PHP version 8.0.2 and I am on Windows 10 OS. I have installed PHP as standalone (without XAMPP for ie.). I have used Non-Threat Safe version, because of my Threat Safety is disabled.

**Comment by sidz** [comment]
Hey.

1.11 is only compatible with PHP 8. But there is an issue with Windows dll. More information you can find:
- here: https://github.com/php-amqp/php-amqp/issues/386
- and here: https://github.com/php-amqp/php-amqp/issues/390

**Comment by cybercitizen7** [comment]
Is my issue the same though? In my case, `amqp.dll `is not being even detected.

**Comment by lstrojny** [comment]
Closing
