### ISSUE TITLE
When will the next stable be released? (with PHP 8 support)

### ISSUE THREAD

**Issue by SemperDisco** [php-amqp/php-amqp#399]
The current version 1.11.0beta works fine with PHP 8, but the stable version before doesn't. Is there an estimated date for when the next stable version will be released which includes the PHP 8 support?

**Comment by ruudk** [comment]
For what it's worth, we've been using 1.11.0beta in production on PHP 8 and don't have encountered any issues :shipit: 😊

**Comment by BenMorel** [comment]
Same here, we've been using `1.11.0beta` for months in production without issues.
That being said, I'd be curious to know if this version is also compatible with upcoming PHP 8.1. @lstrojny?

**Comment by BenMorel** [comment]
@lstrojny Thank you! Will it be compatible with PHP 8.1?

**Comment by lstrojny** [comment]
@BenMorel I haven’t tested it with PHP 8.1, can you check out RC1 and let me know?

**Comment by danilopolani** [comment]
We've been using `1.11.0-beta` for months with PHP8 in production with high-volume messages and no issues so far, hoping for a PHP8.1 release soon 👀

**Comment by kricha** [comment]
any news here?

**Comment by BenMorel** [comment]
Thanks a lot for your work, @lstrojny !

**Comment by yaotzin1** [comment]
DLL for Windows is not compatible with php 8.1

PHP 8.1.1

`PHP Warning:  PHP Startup: amqp: Unable to initialize module
Module compiled with module API=20200930
PHP    compiled with module API=20210902
These options need to match
 in Unknown on line 0

Warning: PHP Startup: amqp: Unable to initialize module
Module compiled with module API=20200930
PHP    compiled with module API=20210902
These options need to match
 in Unknown on line 0`

PHP 8.1
`PS C:\tools\PHP\PHP8\php-8.1.0-Win32-vs16-x64> .\php.exe
PHP Warning:  PHP Startup: amqp: Unable to initialize module
Module compiled with module API=20200930
PHP    compiled with module API=20210902
These options need to match
 in Unknown on line 0

Warning: PHP Startup: amqp: Unable to initialize module
Module compiled with module API=20200930
PHP    compiled with module API=20210902
These options need to match
 in Unknown on line 0`

**Comment by ruudk** [comment]
@yaotzin1 open a new issue please
