### ISSUE TITLE
RabbitMQ stream support

### ISSUE THREAD

**Issue by AhmedSamy** [php-amqp/php-amqp#400]
Feature request to add support for the RabbitMQ streams in version 3.9 
https://blog.rabbitmq.com/posts/2021/07/rabbitmq-streams-overview/

**Comment by Gsantomaggio** [comment]
The stream queues can work using standard AMQP Clients and with a RabbitMQ stream protocol.

RabbitMQ stream protocol.l we have separate clients, see:  https://www.rabbitmq.com/stream.html

See also: https://www.rabbitmq.com/stream-core-plugin-comparison.html

**Comment by lstrojny** [comment]
Stream support through AMQP is already available, as RabbitMQ exposes streams as regular AMQP queues. Stream support with the binary protocol would be too much work. Happy to review and guide a contributor if interest is big enough. Until that happens, I am closing this issue.
