### ISSUE TITLE
Modify the password length limit

### ISSUE THREAD

**Issue by zuozhehao** [php-amqp/php-amqp#406]
https://github.com/php-amqp/php-amqp/blob/a8a293118348343f7fe8648670feac40926875b4/amqp_connection.c#L366-L371

I used the rabbitmq of the cloud service. Its password length is 152. I tried to modify the source code to change 128 to 256. Is there any impact on the use.

**Comment by lstrojny** [comment]
Feel free to open a pull request to increase the maximum password length

**Comment by lstrojny** [comment]
Fixed in #433
