### ISSUE TITLE
Huge disk space and memory usage in using the library

### ISSUE THREAD

**Issue by mathewvp** [php-amqp/php-amqp#408]
When using phpamqp library and using persistent mode for delivery of messages, the messages are getting written under "msg_store_persistent" folder but the size is huge, around 3.8 GB for 4800 messages. Each payload is 1.1KB in size. When using golang library and using persistent mode, using the same payload, the messages are getting written to "queues" folder (still persistent, I restarted AMQP server and tested) and the file size is relatively very small, 49MB for 43000 messages. Why is php amqp library writing to a different folder with such huge size?

Sample code

```
$exchange = new \AMQPExchange($this-_channel);
 $exchange-setName('xxx.push-notification.exg');
 $exchange-setType(AMQP_EX_TYPE_DIRECT);
 $exchange-setFlags(AMQP_DURABLE);
 // declare method deprecated. ref http://php.net/manual/fa/amqpexchange.declare.php
 $exchange-declareExchange();
 $this-_exchange = $exchange;
 
 $queue = new \AMQPQueue($this-_channel);
 $queue-setName('xxx.push-notification.que');
 $queue-setFlags(AMQP_DURABLE);
 $args = array('x-ha-policy' = 'all');
 if ($hasDeadLetter) {
     $args['x-dead-letter-exchange'] = 'xxx.err.exg';
     $args['x-dead-letter-routing-key'] = $queueName;
 }
 $queue-setArguments($args);
 $queue-declareQueue();
 $queue-bind('xxx.push-notification.exg', $routingKey);
 
 $params = array('content_type' => 'text/json', 'delivery_mode'=>2);
 $exchange-publish($msg, $routingKey, false, $params);
```

versions

php amqp: 1.10.2

PHP 7.0.33-50+ubuntu20.04.1+deb.sury.org+1 (cli) (built: May 1 2021 11:50:22) ( NTS )

Rabbitmq 3.7.14 Erlang 21.3.3

OS Ubuntu 16.04.6

**Comment by lukebakken** [comment]
Discussion can be found here - https://github.com/rabbitmq/amqp091-go/discussions/28

@lstrojny feel free to close this issue (php-amqp/php-amqp#408). It is _extremely unlikely_ this issue is due to anything in this library. The RabbitMQ core team is working with @mathewvp to get to the bottom of this in the discussion to which I linked above.

**Comment by lukebakken** [comment]
@lstrojny - this issue (#408) can be closed. This issue turned out to be an error in @mathewvp's code - https://github.com/rabbitmq/amqp091-go/discussions/28#discussioncomment-1743665
