### ISSUE TITLE
version 1.11.0 on windows with php 8.1.1

### ISSUE THREAD

**Issue by Snowbaha** [php-amqp/php-amqp#411]
Hello,

I just installed a fresh php 8.1.1 on windows and I download the relase 1.11.0 of the php amqp but I got this error.
![image](https://user-images.githubusercontent.com/3284722/148985141-bb998772-af82-4d4f-a37a-299a320be528.png)

The changelog write it should work so I don't know what I am missing :(
![image](https://user-images.githubusercontent.com/3284722/148985236-c9bcdd13-e75b-4eed-8c05-50d5e5b4b3e6.png)

**Comment by cmb69** [comment]
> The changelog write it should work so I don't know what I am missing :(

You've tried to use a PHP extension, which was build for PHP 8.0, with PHP 8.1. [amqp 1.11.0 DLLs for PHP 8.1](https://pecl.php.net/package/amqp/1.11.0/windows) are now available.

Looks like this ticket can be closed.

**Comment by Snowbaha** [comment]
I did it with the 1.11.0 so it should work for php8.1 `php_amqp-1.11.0-8.0-ts-vs16-x64`

**Comment by cmb69** [comment]
Ah, right, there have been snapshots from 2021-12-01; please try with the more recently built https://windows.php.net/downloads/pecl/releases/amqp/1.11.0/.

**Comment by Snowbaha** [comment]
Ok thank you! It is working! :)
