### ISSUE TITLE
Can not connect to Amazon MQ.

### ISSUE THREAD

**Issue by atrigub** [php-amqp/php-amqp#413]
Hi guys, I have trouble with connection with Amazon MQ. I use enqueue/amqp-ext, it is trying connect to RMQ, and gets message

"Library error: connection closed unexpectedly - Potential login failure"

php version = 8.1

php-amqp
Version => 1.11.0
Revision => release
Compiled => Dec 16 2021 @ 15:16:37
AMQP protocol version => 0-9-1
librabbitmq version => 0.9.0
Default max channels per connection => 256
Default max frame size => 131072
Default heartbeats interval => 0

**Comment by lyrixx** [comment]
Can you ensure Amazon MQ is configured with RabbitMQ (and not ActiveMQ), and double check the crendentials?

**Comment by atrigub** [comment]
I use another library (php-amqplib) with the same credentials and it works fine.

**Comment by atrigub** [comment]
@lyrixx I checked? Amazon MQ is configured with RabbitMQ, but it still can not connect (

**Comment by trntv** [comment]
The problem with AWS is because of amqps. AWS doesn't provide certificates for it's ampqs connection but this extensions requires them. This is a huge problem because Symfony Messenger (for example) use this extension by default and, as a result, is unusable with AWS out of the box (without third party transports)

**Comment by cuongngoz** [comment]
hi @trntv @atrigub 
Can I ask does it work so far? could you share config example?

**Comment by pgrau** [comment]
it works:

```
class FactoryConnection
{
    public static function create(
        string $vhost,
        string $host,
        string $port,
        string $login,
        string $password
    ): RabbitMqConnection {
        $conf = [
            'vhost' => $vhost,
            'host' => $host,
            'port' => $port,
            'login' => $login,
            'password' => $password,
            'write_timeout' => 5,
            'connect_timeout' => 5,
            'cacert' => '/etc/ssl/certs/Amazon_Root_CA_1.pem',
        ];

        return new RabbitMqConnection($conf);
    }
}
```

**Comment by lstrojny** [comment]
Closing
