### ISSUE TITLE
无法加载，扩展是存在的

### ISSUE THREAD

**Issue by okami-chen** [php-amqp/php-amqp#422]
PHP Warning:  PHP Startup: Unable to load dynamic library 'amqp' (tried: D:\php\8.1\ext\amqp (鎵句笉鍒版寚瀹氱殑妯″潡銆?, D:\php\8.1\ext\php_amqp.dll (鎵句笉鍒版寚瀹氱殑妯″潡銆?) in Unknown on line 0
PHP 8.1.12 (cli) (built: Oct 25 2022 18:20:48) (NTS Visual C++ 2019 x64)

**Comment by okami-chen** [comment]
dll exist: D:\php\8.1\ext\php_amqp.dll

**Comment by okami-chen** [comment]
dll version: [8.1 Non Thread Safe (NTS) x64](https://windows.php.net/downloads/pecl/releases/amqp/1.11.0/php_amqp-1.11.0-8.1-nts-vs16-x64.zip)

**Comment by lstrojny** [comment]
Not enough info to proceed
